### ISSUE TITLE
加入多人协作功能

### ISSUE THREAD

**Issue by MCSeekeri** [HexoPlusPlus/HexoPlusPlus#21]
目前HPP只能是给博主本人管理,希望之后加入多账户功能,这样可以降低非技术人员使用Hexo的成本,同时方便合作博客的撰写。

~~简单来讲就是干翻语雀和yuque-hexo~~

另外...如果纯Vercel不行那Vercel配LeanCloud可能是个不错的方式,参考Waline的成功经验（
Cloudflare Workers对免费用户的限制还是有点多（

**Comment by ChenYFan** [comment]
多账户简单，登陆用户名和密码以字典存储就可以了。
leancloud是不可能的，流控问题，数据库经常炸。
> Cloudflare Workers对免费用户的限制还是有点多（

比如？我个人认为免费用户的限制已经相当合理了

**Comment by ChenYFan** [comment]
0.1.2版本已实现https://github.com/HexoPlusPlus/HexoPlusPlus/raw/dev/dist/index.js

**Comment by MCSeekeri** [comment]
其实好好用是够的但我还是想再嫖点（

好了认真的,富文本编辑器可以进一步优化,参考HexoEditor,能通过读取_config.yml实现自定义设置（

**Comment by ChenYFan** [comment]
富文本编辑器不会再大更改了，本来选择这个就是不要预览版本，自定义设置直接js传递前端就行了

**Comment by MCSeekeri** [comment]
那么有没有可能性通过保存Workers API Token实现自我更新之类的（

（我还没去看Cloudflare文档,应该可以罢.....


（总之我目前就是想到啥说啥,能提一点建议是一点（

**Comment by ChenYFan** [comment]
> 那么有没有可能性通过保存Workers API Token实现自我更新之类的（ （我还没去看Cloudflare文档,应该可以罢..... （总之我目前就是想到啥说啥,能提一点建议是一点（

可以实现，但这是另一个功能了。

**Comment by MCSeekeri** [comment]
> > 那么有没有可能性通过保存Workers API Token实现自我更新之类的（ （我还没去看Cloudflare文档,应该可以罢..... （总之我目前就是想到啥说啥,能提一点建议是一点（
> 
> 可以实现，但这是另一个功能了。

因为我技术能力不大够所以只能想到什么建议提什么建议（
主要是不想开新issue了（

另外...似乎多人协作已经加入了...

**Comment by ChenYFan** [comment]
欸等等，我这还是测试版，还没发真实版呢

**Comment by ChenYFan** [comment]
V0.1.3正式版已实现
