### ISSUE TITLE
[错误] 说说 CSS 错误

### ISSUE THREAD

**Issue by oCoke** [HexoPlusPlus/HexoPlusPlus#50]
## 描述

说说的 CSS 命名可能会与原页面的其他 CSS 元素重复，造成页面混乱。

## 解决方法

更改 CSS 命名（添加前缀等），尽可能是页面元素不重复。

**Comment by oCoke** [comment]
已创建新的分支 [`oCoke:talk-css`](https://github.com/oCoke/HexoPlusPlus/tree/talk-css) 修复此错误，修复完毕后会提交 PR。

**Comment by ChenYFan** [comment]
OK，我很期待

**Comment by ChenYFan** [comment]
已合并[#54](https://github.com/HexoPlusPlus/HexoPlusPlus/pull/54)
