### ISSUE TITLE
[错误] 无法管理 _posts 子目录下的文章

### ISSUE THREAD

**Issue by imaegoo** [HexoPlusPlus/HexoPlusPlus#59]
我的博客文章是按年份放在子目录中的

![图片](https://user-images.githubusercontent.com/20182252/107194624-3d543980-6a2b-11eb-9c1f-960a8a41afe1.png)

在后台无法管理这些文章

![图片](https://user-images.githubusercontent.com/20182252/107194731-65439d00-6a2b-11eb-803d-d5d823a33f8c.png)

**Comment by ChenYFan** [comment]
！

**Comment by ChenYFan** [comment]
HexoPlusPlus@1.1.1_β_5 DEV已修复，请通过小白鼠专属通道更新一次，如果没有问题，该issues将在合并后关闭

【/hpp/admin/api/small_white_mouse_update】

**Comment by imaegoo** [comment]
验证通过，谢谢！

![verified](https://user-images.githubusercontent.com/20182252/107300135-d890f180-6ab3-11eb-9f5e-4f6534d0e470.png)

**Comment by ChenYFan** [comment]
Thanks！

**Comment by ChenYFan** [comment]
1.1.1已修复
