### ISSUE TITLE
[错误]1.2.0-beta版本暗色模式下图片放大出错

### ISSUE THREAD

**Issue by 2X-ercha** [HexoPlusPlus/HexoPlusPlus#67]
如图所示，放大后左边部分被盖住
![image](https://user-images.githubusercontent.com/72645310/108006906-97f72200-7037-11eb-85b9-caf763a99ec0.png)

**Comment by ChenYFan** [comment]
插件问题；若在发布前没有找到更好地代替插件，1.2.0正式版将会移除此插件

**Comment by ChenYFan** [comment]
其实不是暗色的情况下也会复现此问题

**Comment by ChenYFan** [comment]
HexoPlusPlus@1.2.0_β_15已更换新的放大插件，请通过小白鼠通道更新

若没有问题，该issues将在合并后关闭

**Comment by 2X-ercha** [comment]
ok

**Comment by ChenYFan** [comment]
还没合并...

**Comment by ChenYFan** [comment]
已合并
