### ISSUE TITLE
[建议]新建文章时自动添加Front-Matter

### ISSUE THREAD

**Issue by lbr77** [HexoPlusPlus/HexoPlusPlus#68]
每次新建文章时复制很麻烦

**Comment by lbr77** [comment]
~~不知道大佬们怎么做的~~

**Comment by ChenYFan** [comment]
hexo允许从本地模板库中获取frontmatter，但是存在丢失的可能性，此功能滞后

**Comment by 2X-ercha** [comment]
其实旁边新增一个Front-Matter小贴士就行（逃）

**Comment by ChenYFan** [comment]
太操蛋了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "noionion"<notifications@github.com&gt;; 
发送时间: 2021年2月18日(星期四) 晚上8:08
收件人: "HexoPlusPlus/HexoPlusPlus";
抄送: "Comment";
主题: Re: [HexoPlusPlus/HexoPlusPlus] [建议]新建文章时自动添加Front-Matter (#68)





 
其实旁边新增一个Front-Matter小贴士就行（逃）
 
&mdash;

**Comment by ChenYFan** [comment]
1.2.0DEV8已实现该功能，请通过小白鼠更新通道获取此版本

若没有问题，该issues将在合并后关闭

1.2.0
1.增加工具箱功能
2.支持暗色模式
3.支持列表分页
4.支持获取模板

**Comment by ChenYFan** [comment]
已合并
