### ISSUE TITLE
[Bug]图片Repo的CDN链接不支持子目录

### ISSUE THREAD

**Issue by MCSeekeri** [HexoPlusPlus/HexoPlusPlus#69]
嗯...像之前那个bug一样（
![](https://7.dusays.com/2021/02/16/63b3a291bfb4a.jpg)
就拿图片1举例子
点击CDN链接跳转到https://cdn.jsdelivr.net/gh/MCSeekeri/SciadvFiles@master/1.webp
但是点击原始地址则是https://raw.githubusercontent.com/MCSeekeri/SciadvFiles/master/Novel/8bit/1.webp
似乎HPP在搞图片jsd时只是简单的`标准格式/用户/Repo/文件名`,没有考虑到子文件夹（

**Comment by oCoke** [comment]
我记得在设置中有个图片上传文件夹。

**Comment by MCSeekeri** [comment]
嗯...确实是有,但我这的问题是图片Repo里有一堆按文件夹分类的图片,并不是Repo里单独的某个目录...
好吧可能与上传逻辑有关...上传时是没有文件夹选项...

确实也可以新建一个上传专用文件夹,但目前的问题是图片Repo的图片HPP能获取到,但生成的jsdelivr链接不对劲（

**Comment by ChenYFan** [comment]
Yes，图片上传不支持多路径

**Comment by ChenYFan** [comment]
因为使用多路径获取图片的话，删除图片一逻辑要大更，并且hpp尚无多文件夹管理图片的需求。因为图片获取的时候用的也是dfs，但删除的话是先获取列表再获取哈希，所以多文件夹能列出来但是jsd和功能使用会受到限制。
本**特性**目前无修复计划
