### ISSUE TITLE
[建议]提个小小的建议，希望作者用DeepCode（免费版）提高下代码安全性与流畅度

### ISSUE THREAD

**Issue by 2926295173** [HexoPlusPlus/HexoPlusPlus#77]
![deepcode](https://avatars.githubusercontent.com/ml/6366?s=140&v=4)
[deepcode app](https://github.com/marketplace/deepcodeai)
DeepCode查找在代码中解决的错误和关键漏洞。DeepCode的高级代码审查您在进行生产之前节省时间查找和修复错误。

## for example
![](https://marketplace-screenshots.githubusercontent.com/6366/cbd4a680-387d-11ea-93d6-4cb88adbb7ef?auto=webp&format=jpeg&width=670&dpr=1.5)

**Comment by ChenYFan** [comment]
感谢！DEV分支已经在重构整个代码了

**Comment by ChenYFan** [comment]
DEV整个重新上来大概要五月底了

**Comment by ChenYFan** [comment]
流畅度麻烦不要再说了，要是不流畅【10ms】hpp整个程序就会被踢出v8隔离株了

**Comment by 2926295173** [comment]
感谢大佬采取建议，麻烦了。
