### ISSUE TITLE
文档部分出现undefined问题。

### ISSUE THREAD

**Issue by tabris233** [HexoPlusPlus/HexoPlusPlus#78]
场景是第一次配置时因文档相关配置有问题，url错误，导致`bfs_fetch`调用异常最后返回这个json对象`{}`。（对应图1中的1⃣️）
KV中`hpp_doc_list_index` 缓存了"{}" 这个字符串， （对应图1中的3⃣️，图2中红圈部分）

当更正配置后， 因KV中`hpp_doc_list_index`缓存问题 `if (hpp_doc_list_index === null)`这个逻辑永远不会命中。（对应图1中的2⃣️）
![image](https://user-images.githubusercontent.com/29500388/113473324-91afee80-949b-11eb-8eb3-4dbbe55044ac.png)

![image](https://user-images.githubusercontent.com/29500388/113473247-fdde2280-949a-11eb-8777-b32a3bbcf2c0.png)

------

解决办法我这里有两个：
1. 手动删除索引。可以在hpp页面中，也可以在workers的KV管理页面。 建议把这个放到 https://hexoplusplus.js.org/faq/ 中
![image](https://user-images.githubusercontent.com/29500388/113473432-0be07300-949c-11eb-8ee1-c6612a148fee.png)
2. 修改代码兼容下
![image](https://user-images.githubusercontent.com/29500388/113473468-3df1d500-949c-11eb-9d0d-61f6648b6620.png)

**Comment by ChenYFan** [comment]
这种情况下本来就要求您手动清除缓存，空`{}`是可能并合理存在的，此段无需重构

**Comment by ChenYFan** [comment]
这种情况下本来就要求您手动清除缓存，空`{}`是可能并合理存在的，此段无需重构
