### ISSUE TITLE
[请求添加功能] 每发布一次文章更新Sitemap.xml

### ISSUE THREAD

**Issue by samleong123** [HexoPlusPlus/HexoPlusPlus#81]
希望可以每次发布文章后更新 Sitemap.xml , 这样就不需要本地运行 ```hexo g``` 了.

**Comment by 2X-ercha** [comment]
你有装sitemap插件的话构建的时候是会更新的。每一次修改文章都会帮你构建一次

**Comment by ChenYFan** [comment]
sitemap是hexo帮你构建的，hpp做不到。。。此要求并非HPP所能实现

你可以安装 hexo-sitemap 插件来实现
