### ISSUE TITLE
文档获取出现undefined

### ISSUE THREAD

**Issue by chen8945** [HexoPlusPlus/HexoPlusPlus#92]
### **我是文档里所写的步骤进行的**  
![QQ截图20210811212026.png](https://i.loli.net/2021/08/11/AmFyDnjxGuCYipc.png)  
### **图片能正常获取但是文档获取失败,token我也反复检查过好几次没有出现错误**  
![QQ截图20210811212047.png](https://i.loli.net/2021/08/11/2sPQIjHpcNtBYLo.png)  
### **以下是我的源代码目录以及配置截图**  
![QQ截图20210811211950.png](https://i.loli.net/2021/08/11/iOHYvCs97QUuykI.png)  
![QQ截图20210811212015.png](https://i.loli.net/2021/08/11/ph9FXJYTMWGxuQO.png)

**Comment by ChenYFan** [comment]
清除缓存。。。

**Comment by chen8945** [comment]
> 清除缓存。。。

清过了

**Comment by ChenYFan** [comment]
> > 清除缓存。。。
> 
> 清过了

我指的是编辑页面红色按钮

**Comment by chen8945** [comment]
> > > 清除缓存。。。
> > 
> > 
> > 清过了
> 
> 我指的是编辑页面红色按钮-清除索引

那个徒手清索引对吧，那个我点过好多次了

**Comment by ChenYFan** [comment]
> > > > 清除缓存。。。
> > > 
> > > 
> > > 清过了
> > 
> > 
> > 我指的是编辑页面红色按钮-清除索引
> 
> 那个徒手清索引对吧，那个我点过好多次了

token有读取私有仓库的权限嘛

**Comment by chen8945** [comment]
> > > > > 清除缓存。。。
> > > > 
> > > > 
> > > > 清过了
> > > 
> > > 
> > > 我指的是编辑页面红色按钮-清除索引
> > 
> > 
> > 那个徒手清索引对吧，那个我点过好多次了
> 
> token有读取私有仓库的权限嘛

有，一开始我也以为权限问题，后来我就尝试了一下新建token全开权限都没用

**Comment by ChenYFan** [comment]
实在不行加群说吧，我给你开一下调试模式

**Comment by BillScott1024** [comment]
请问解决了嘛？我也遇到相同的问题了
![XXC_NPJ4MHXAF)P_X6 KYW4](https://user-images.githubusercontent.com/22955480/141819770-9e4efd3f-3cd3-4f5c-b6f0-79ec0442306a.png)

![image](https://user-images.githubusercontent.com/22955480/141819795-08c6deb4-fc12-42b4-aa2d-b3b1c6ed3085.png)
