### ISSUE TITLE
啥时候能加入对Gitlab的支持啊～～

### ISSUE THREAD

**Issue by crisqyxw** [HexoPlusPlus/HexoPlusPlus#93]
大佬求你了，Gitlab众已经馋得流口水了～

**Comment by fmkli** [comment]
总所周知，咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕

**Comment by crisqyxw** [comment]
> 总所周知，咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕

口水不争气的从嘴里流出，但是只能干看着，羡慕啊。。。

**Comment by ChenYFan** [comment]
已加入日程表，但什么时候发布就不好说了（

**Comment by crisqyxw** [comment]
> 已加入日程表，但什么时候发布就不好说了（

好耶！
